# Generated by Django 5.2.5 on 2025-08-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tests/'),
        ),
        migrations.AddField(
            model_name='tests',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='result',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_type',
            field=models.CharField(max_length=100),
        ),
    ]
