# Generated by Django 5.2.5 on 2025-08-19 20:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_tests_image_tests_image_url_tests_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
